### ISSUE TITLE
thermal throttling

### ISSUE THREAD

**Issue by helloaziz** [sergliga/MSI-GF63-9SCSR-BigSur-#1]
fan working properly? I have a problem, fans works so slow, I mean basically doesnt work and what can I do for fix that? I tried using MSIFanControl kext but nothing.

**Comment by sergliga** [comment]
> fan working properly? I have a problem, fans works so slow, I mean basically doesnt work and what can I do for fix that? I tried using MSIFanControl kext but nothing.

Same problem, so i decided to undervolt core in bios. -85 mV solved any issues with throttling and slow fans. I tested for hours, continuously on 4.0Mhz temp not higher than 75.

**Comment by helloaziz** [comment]
how 

> > fan working properly? I have a problem, fans works so slow, I mean basically doesnt work and what can I do for fix that? I tried using MSIFanControl kext but nothing.
> 
> Same problem, so i decided to undervolt core in bios. -85 mV solved any issues with throttling and slow fans. I tested for hours, continuously on 4.0Mhz temp not higher than 75.

![image](https://user-images.githubusercontent.com/13496523/137880605-51537788-05fc-41d0-9075-6f37995a754e.png)
the ssdt not working? btw how to underclock cpu in bios?

**Comment by sergliga** [comment]
> how 
> 
> 
> 
> > > fan working properly? I have a problem, fans works so slow, I mean basically doesnt work and what can I do for fix that? I tried using MSIFanControl kext but nothing.
> 
> > 
> 
> > Same problem, so i decided to undervolt core in bios. -85 mV solved any issues with throttling and slow fans. I tested for hours, continuously on 4.0Mhz temp not higher than 75.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/13496523/137880605-51537788-05fc-41d0-9075-6f37995a754e.png)
> 
> the ssdt not working? btw how to underclock cpu in bios?

This ssdt is working (without it my fans not spinning at all when idle) 
In BIOS press right shift + right ctrl + left alt + F2

Go to advanced > overclocking performance menu > 
Set overclocking feature, WTD, XTU to enabled. 
Then go to processor and set  -85 mV
![image](https://user-images.githubusercontent.com/24439930/137891663-d7ba5be3-5d6f-4512-baa6-2824f179c1b4.jpeg)
![image](https://user-images.githubusercontent.com/24439930/137891735-dd15e1c6-b49a-402d-9d3a-b96a3b38173d.jpeg)

**Comment by helloaziz** [comment]
> > how
> > > > fan working properly? I have a problem, fans works so slow, I mean basically doesnt work and what can I do for fix that? I tried using MSIFanControl kext but nothing.
> > 
> > 
> > > 
> > 
> > 
> > > Same problem, so i decided to undervolt core in bios. -85 mV solved any issues with throttling and slow fans. I tested for hours, continuously on 4.0Mhz temp not higher than 75.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/13496523/137880605-51537788-05fc-41d0-9075-6f37995a754e.png)
> > the ssdt not working? btw how to underclock cpu in bios?
> 
> This ssdt is working (without it my fans not spinning at all when idle) In BIOS press right shift + right ctrl + left alt + F2
> 
> Go to advanced > overclocking performance menu > Set overclocking feature, WTD, XTU to enabled. Then go to processor and set -85 mV ![image](https://user-images.githubusercontent.com/24439930/137891663-d7ba5be3-5d6f-4512-baa6-2824f179c1b4.jpeg) ![image](https://user-images.githubusercontent.com/24439930/137891735-dd15e1c6-b49a-402d-9d3a-b96a3b38173d.jpeg)

one more thing, did ur webcam work perfectly like in windows?

**Comment by sergliga** [comment]
> one more thing, did ur webcam work perfectly like in windows?

Yes, same on windows. Activated via FN F6. But first must be mapped via USBMap. 
As you can see on my machine its connected to HS11![image](https://user-images.githubusercontent.com/24439930/137893043-56c5d8f1-87e0-43c1-a0f7-2fbf84c47d6b.jpeg)

**Comment by helloaziz** [comment]
> > one more thing, did ur webcam work perfectly like in windows?
> 
> Yes, same on windows. Activated via FN F6. But first must be mapped via USBMap. As you can see on my machine its connected to HS11![image](https://user-images.githubusercontent.com/24439930/137893043-56c5d8f1-87e0-43c1-a0f7-2fbf84c47d6b.jpeg)

ok, thank you, i will try ur efi folder later

**Comment by sergliga** [comment]
> ok, thank you, i will try ur efi folder later

I'm now on beta 10. On newer monterey builds bluetooth not working.

**Comment by helloaziz** [comment]
> > ok, thank you, i will try ur efi folder later
> 
> I'm now on beta 10. On newer monterey builds bluetooth not working.
![Screen Shot 2021-10-21 at 05 56 13](https://user-images.githubusercontent.com/13496523/138183834-30b60ea1-d599-461a-9ea0-7a17f94ffc18.png)
did u know how to fix my webcam? its always black
