### ISSUE TITLE
Audio and bluetooth not working

### ISSUE THREAD

**Issue by RubenOliveira8** [sergliga/MSI-GF63-9SCSR-BigSur-#2]
i'v tried on my msi gf63 9rcx and audio and bluetooth aren't working, i'v tried to update my Big Sur OpenCore 0.6.9 to the latest to try make it bootable for Monterey but it did't work just stuck on apple logo, what settings need to be changed on OpenCore to get it running comparing to Big Sur. thanks

**Comment by sergliga** [comment]
> i'v tried on my msi gf63 9rcx and audio and bluetooth aren't working, i'v tried to update my Big Sur OpenCore 0.6.9 to the latest to try make it bootable for Monterey but it did't work just stuck on apple logo, what settings need to be changed on OpenCore to get it running comparing to Big Sur. thanks

You may try to compare my opencore settings with yours step by step. For audio you should try another "layout id". 
For bluetooth it seems need to wait for update bluetool kext. So the best decision to buy BCM94360NG.

**Comment by RubenOliveira8** [comment]
Actualy, i got audio and bluetooth working, audio was the layout id and bluetooth was the bluetoolfix kext version that was not making it work, i just download a newer version from a forum and it worked, but for hdmi, on my last opencore for big sur, i was able to use enable-hdmi20 on the device property of intel uhd but on this one semes to not work, even trying to change the entire device property of yours efi with my old efi but it does not work too, maybe it is related to aml files on the acpi folder, for now this is working well, nice work you have do!

**Comment by RubenOliveira8** [comment]
UPDATE : 
Managed to get hdmi video and soud working, but for some reason keyboard is not working in bios, boot menu and opencore after restarting from mac, i'v tried to figure out what was causing this but did not found, i'v need to force shutdown the laptop to bring back the keyboard to bios and boot options.

**Comment by sergliga** [comment]
> UPDATE : 
> 
> Managed to get hdmi video and soud working, but for some reason keyboard is not working in bios, boot menu and opencore after restarting from mac, i'v tried to figure out what was causing this but did not found, i'v need to force shutdown the laptop to bring back the keyboard to bios and boot options.

I experienced same issue before. After deleted some acpi problem gone. Post your acpi list here. 
If you have ps2key.aml try without it.

**Comment by RubenOliveira8** [comment]
> > UPDATE :
> > Managed to get hdmi video and soud working, but for some reason keyboard is not working in bios, boot menu and opencore after restarting from mac, i'v tried to figure out what was causing this but did not found, i'v need to force shutdown the laptop to bring back the keyboard to bios and boot options.
> 
> I experienced same issue before. After deleted some acpi problem gone. Post your acpi list here. If you have ps2key.aml try without it.

i'v forked your repo and added my efi folder instead, you can see all the acpi files i got.

**Comment by sergliga** [comment]
> i'v forked your repo and added my efi folder instead, you can see all the acpi files i got.

Try to cold boot without TPD0.aml
Shutdown. Unplug AC cable. Push reset button on the bottom of your computer for 30s. Plug in AC. Boot.

**Comment by RubenOliveira8** [comment]
> > i'v forked your repo and added my efi folder instead, you can see all the acpi files i got.
> 
> Try to cold boot without TPD0.aml Shutdown. Unplug AC cable. Push reset button on the bottom of your computer for 30s. Plug in AC. Boot.

did not work, after reset it was working, but i booted into mac and restarted and it did stop working again.

**Comment by sergliga** [comment]
> did not work, after reset it was working, but i booted into mac and restarted and it did stop working again.

You may try to use mine 3 voodoo kext instead of yours. 
Make sure they loaded exact in the same order. In past i got a lot of headache with them. Please note that I2C and PS2 duplicating VoodooInput. You should set enabled only PS2 VoodooInput.

**Comment by sergliga** [comment]
> Actualy, i got audio and bluetooth working, audio was the layout id and bluetooth was the bluetoolfix kext version that was not making it work, i just download a newer version from a forum and it worked, but for hdmi, on my last opencore for big sur, i was able to use enable-hdmi20 on the device property of intel uhd but on this one semes to not work, even trying to change the entire device property of yours efi with my old efi but it does not work too, maybe it is related to aml files on the acpi folder, for now this is working well, nice work you have do!

How do you repair hdmi? After framebuffer patching i only got hdmi video but never audio. 🤷

**Comment by RubenOliveira8** [comment]
> > Actualy, i got audio and bluetooth working, audio was the layout id and bluetooth was the bluetoolfix kext version that was not making it work, i just download a newer version from a forum and it worked, but for hdmi, on my last opencore for big sur, i was able to use enable-hdmi20 on the device property of intel uhd but on this one semes to not work, even trying to change the entire device property of yours efi with my old efi but it does not work too, maybe it is related to aml files on the acpi folder, for now this is working well, nice work you have do!
> 
> How do you repair hdmi? After framebuffer patching i only got hdmi video but never audio. 🤷

after getting hdmi video port working, you need to set device id and hda-gfx settings to device properties of the audio device, i'v attached two screenshots of my DeviceProperties.
![Captura de ecrã 2021-10-31, às 11 33 57](https://user-images.githubusercontent.com/30351208/139578522-bfdd3090-e2a4-4b85-aac2-74a9735fb607.png)
![Captura de ecrã 2021-10-31, às 11 33 37](https://user-images.gi
![Captura de ecrã 2021-10-31, às 11 39 15](https://user-images.githubusercontent.com/30351208/139578696-8b60038f-6981-4d0a-b29c-a8567454e3bb.png)
thubusercontent.com/30351208/139578520-54b7c5db-9940-4ef6-9ad4-8e7b99d3a3c6.png)

**Comment by sergliga** [comment]
> after getting hdmi video port working, you need to set device id and hda-gfx settings to device properties of the audio device, i'v attached two screenshots of my DeviceProperties. 

Thank's it's solve the problem!

**Comment by RubenOliveira8** [comment]
> > after getting hdmi video port working, you need to set device id and hda-gfx settings to device properties of the audio device, i'v attached two screenshots of my DeviceProperties. 
> 
> 
> 
> Thank's it's solve the problem!
> 
> 

Your welcome, but i still did't find what is making my keyboard to stop working on biod, i´v tried everything, can you update your efi on github with your new working version that has hdmi, did you tried the bluetoolfixup moded version from riposte94, the one that comes on your efi folder actualy does not work on many motherboards and that includes mine, maybe the dev will officialy update it soon but for now i will stand on this version.

**Comment by sergliga** [comment]
> Your welcome, but i still did't find what is making my keyboard to stop working on biod, i´v tried everything, can you update your efi on github with your new working version that has hdmi, did you tried the bluetoolfixup moded version from riposte94, the one that comes on your efi folder actualy does not work on many motherboards and that includes mine, maybe the dev will officialy update it soon but for now i will stand on this version.

Now updated. After Monterey beta 8 I swapped wifi card to BCM94360NGso I don't have any kext related to Wifi or Bluetooth.
On my experience bluetooth stop working after Beta 10. Before everything was fine with latest kexts:
1. AirportItlwm
2. BlueToolFixup
3. IntelBluetoothFirmware

**Comment by RubenOliveira8** [comment]
You forget to change hda-gfx type to string and the value have automaticly change to an incorrect set of binary bits

**Comment by sergliga** [comment]
> You forget to change hda-gfx type to string and the value have automaticly change to an incorrect set of binary bits

Fixed. Thank's.
