### ISSUE TITLE
unable to make it boot 

### ISSUE THREAD

**Issue by nagulan51** [sergliga/MSI-GF63-9SCSR-BigSur-#3]
can you give me more details about bios configuration !

**Comment by sergliga** [comment]
> can you give me more details about bios configuration !
> 
> 

Change BIOS settings

1. Show hidden settings with: CTRL Right + SHIFT Right + ALT Left + F2
2. Turn off Secure Boot [Security]
3. Turn off CFG Lock [Advanced -> Power & Performance -> CPU -> CPU Lock Configuration]
4. Disable Fast Boot [Boot]
5. Select UEFI mode without CSM [Boot]

**Comment by nagulan51** [comment]
![image](https://user-images.githubusercontent.com/21207624/147386109-8a340dd0-de43-4d31-8b62-687f391cff14.jpeg) hi thank you very much but I'm
Unable to see the disk i Already copied the efi partition can you help me ? , it's booting without no problem on the usb

**Comment by sergliga** [comment]
> hi thank you very much but I'm
> Unable to see the disk i Already copied the efi partition can you help me ? , it's booting without no problem on the usb 

Use the Shell.efi to boot into UEFI Shell, then run the following command:

**bcfg boot dump**
This command will output result of your BIOS boot partitiions. If the result is empty you need to add a new Boot record.

First, run **map** to find your MacOS installation drive. Take note on the FS* drive letter. eg. FS4.

To add a new Boot record, run the following command:

bcfg boot add 05 FS*:\EFI\OC\opencore.efi OpenCore

**Comment by sergliga** [comment]
> > hi thank you very much but I'm
> > Unable to see the disk i Already copied the efi partition can you help me ? , it's booting without no problem on the usb 
> 
> Use the Shell.efi to boot into UEFI Shell, then run the following command:
> 
> **bcfg boot dump**
> This command will output result of your BIOS boot partitiions. If the result is empty you need to add a new Boot record.
> 
> First, run **map** to find your MacOS installation drive. Take note on the FS* drive letter. eg. FS4.
> 
> To add a new Boot record, run the following command:
> 
> bcfg boot add 05 FS*:\EFI\OC\opencore.efi OpenCore
> 
> 

Did you copy EFI folder to same partition with windows EFI? If yes, EfiShell should help. 

And if you used a separate one, probably adding boot record will not help. Try to add you hackintosh Efi folder to origin Efi partition with windows Efi folder.

**Comment by nagulan51** [comment]
i have tried to add with windows efi but didn't work !

**Comment by sergliga** [comment]
> i have tried to add with windows efi but didn't work !

Did you try to add boot option manually as I mention above?
This is the only way for msi laptop.

**Comment by nagulan51** [comment]
yeah maybe did it the wrong way , is there any guide on ytb for that ?

**Comment by sergliga** [comment]
> yeah maybe did it the wrong way , is there any guide on ytb for that ?
> 
> 
You may try this: https://nxw.name/amp/33125

Just in last step you should use this instead:

bcfg boot add BOOTID DISKID:\EFI\OC\Opencore.efi OpenCore

**Comment by nagulan51** [comment]
i m unable to find the boot id could you help me ?

**Comment by sergliga** [comment]
> i m unable to find the boot id could you help me ?
> 
> 

Try 05

**Comment by nagulan51** [comment]
![image](https://user-images.githubusercontent.com/21207624/147416886-26113eba-e089-4e80-bf86-faec244dd481.jpeg)

**Comment by nagulan51** [comment]
![image](https://user-images.githubusercontent.com/21207624/147416936-89026e00-a317-4286-999f-f1a59ca0661d.jpeg)
