### ISSUE TITLE
opencore version

### ISSUE THREAD

**Issue by phes10529** [sergliga/MSI-GF63-9SCSR-BigSur-#4]
Hello, let me ask a question. I use your EFI to check the opencore version through hackintool and it shows that the opencore version is 0.6.5, which is different from the OpenCore 0.7.4 you mentioned. I want to confirm the OpenCore version with you again, thank you

**Comment by sergliga** [comment]
> Hello, let me ask a question. I use your EFI to check the opencore version through hackintool and it shows that the opencore version is 0.6.5, which is different from the OpenCore 0.7.4 you mentioned. I want to confirm the OpenCore version with you again, thank you

Hello, It's 0.7.4.
