### ISSUE TITLE
Camera not working

### ISSUE THREAD

**Issue by phes10529** [sergliga/MSI-GF63-9SCSR-BigSur-#5]
MSI GF75 thin 9sc Camera not working,Configuration Same with you ,just CPU is I7-9650h , GPU is GTX 1650,in system report show No video capture devices ,From WIN10, I confirmed that the camera can be started

**Comment by sergliga** [comment]
> MSI GF75 thin 9sc Camera not working,Configuration Same with you ,just CPU is I7-9650h , GPU is GTX 1650,in system report show No video capture devices ,From WIN10, I confirmed that the camera can be started

Did you switch it on by pressing FN + F6?
